swagger: '2.0'
info:
  title: testi-deletetoken-api
  version: 1.0.0
schemes:
  - https
produces:
  - application/json
paths:
  /testi:
    post:
      summary: deletes the token from the database
      operationId: testifunktio
      x-google-backend:
        address: FUNKTIOURL 
      responses:
        '200':
          description: A successful response
          schema:
            type: string
    options:
      operationId: corstestifunktio
      x-google-backend:
        address: FUNKTIOURL
      responses:
        '200':
          description: A successful response