swagger: '2.0'
info:
  title: kekkos-api-config
  version: 1.0.0
schemes:
  - https
produces:
  - application/json
paths:
  /poisto:
    delete:
      summary: deletes the token from the database
      operationId: delete-token
      x-google-backend:
        address: https://us-central1-final-project-2-337107.cloudfunctions.net/poistatoken
      responses:
        '200':
          description: A successful response
          schema:
            type: string
    options:
      operationId: cors-delete
      x-google-backend:
        address: https://kekkoslovakia-front-prod-7a6ps2xuoq-ew.a.run.app
      responses:
        '200':
          description: A successful response
  /lisays:
    post:
      summary: adds an event to the database
      operationId: lisaa-token
      x-google-backend:
        address: https://us-central1-final-project-2-337107.cloudfunctions.net/lisaatoken
      responses:
        '200':
          description: A successful response
          schema:
            type: string
    options:
      operationId: cors-lisaa
      x-google-backend:
        address: https://kekkoslovakia-front-prod-7a6ps2xuoq-ew.a.run.app
      responses:
        '200':
          description: A successful response
  /hae:
    get:
      summary: gets a card from the db
      operationId: hae-kortti
      x-google-backend:
        address: https://us-central1-final-project-2-337107.cloudfunctions.net/haekortti
      responses:
        '200':
          description: A successful response
          schema:
            type: string
    options:
      operationId: cors-hae
      x-google-backend:
        address: https://kekkoslovakia-front-prod-7a6ps2xuoq-ew.a.run.app
      responses:
        '200':
          description: A successful response
  /haekaikki:
    get:
      summary: get all cards from the db
      operationId: hae-kaikki
      x-google-backend:
        address: https://us-central1-final-project-2-337107.cloudfunctions.net/haekaikki
      responses:
        '200':
          description: A successful response
          schema:
            type: string
    options:
      operationId: cors-hae-kaikki
      x-google-backend:
        address: https://kekkoslovakia-front-prod-7a6ps2xuoq-ew.a.run.app
      responses:
        '200':
          description: A successful response